set -x
while read num name junk
do
    go run /home/strick/modoc/coco-shelf/copico-bonobo/gen_metadata_uf2/gen_metadata_uf2.go \
        -label p=1,b=centipede,v=32z,mhz=250,seed=`uuidgen`,h=pizga.net,name=$name,id=z$num

    read wait < /dev/tty

    cp -v /tmp/centipede-watcher.uf2 /media/strick/RP2350/

    read wait < /dev/tty

    cp -v _metadata.uf2 /media/strick/RP2350/

    read wait < /dev/tty

done << END
     00 Zootar
     01	Vernelix (Vernal + Helix)
     02	Floramble (Flora + Ramble)
     03	Mossaur (Moss + Dinosaur)
     04	Bloomber (Bloom + Timber)
     05	Leaflit (Leaf + Kit)
     06	Thornix (Thorn + Phoenix)
     07	Petalisk (Petal + Basilisk)
     08	Rootar (Root + Star)
     09	Budbug (Bud + Bug)
    10	Vinelix (Vine + Helix)
    11	Leaflyre (Leaf + Lyre)
    12	Mosskin (Moss + Kin)
    13	Fernflare (Fern + Flare)
    14	Barkron (Bark + Iron)
    15	Sprigkit (Sprig + Kit)
    16	Pyrowag (Pyro + Wagtail)
    17	Ignisnek (Igni + Snake)
    18	Scorchum (Scorch + Opossum)
    19	Charunt (Char + Runt)
    20	Flamerat (Flame + Rat)
    21	Burnadillo (Burn + Armadillo)
    22	Emberon (Ember + Heron)
    23	Blazeling (Blaze + Starling)
    24	Pyropaw (Pyro + Paw)
    25	Magmunkey (Magma + Monkey)
    26	Searat (Sear + Rat)
    27	Heatorch (Heat + Torch)
    28	Ashite (Ash + Suffix)
    29	Flickerose (Flicker + Rose)
    30	Cinderish (Cinder + Fish)
    31	Aqualth (Aqua + Stealth)
    32	Hydrip (Hydro + Drip)
    33	Maridrip (Marine + Drip)
    34	Bubblora (Bubble + Flora)
    35	Wavetoe (Wave + Toe)
    36	Gushark (Gush + Shark)
    37	Dewdrol (Dew + Droll)
    38	Aquapup (Aqua + Pup)
    39	Splashling (Splash + Gosling)
    40	Tidalth (Tidal + Stealth)
    41	Streamit (Stream + Bit)
    42	Coralith (Coral + Lith)
    43	Shellus (Shell + Suffix)
    44	Gushon (Gush + Suffix)
    45	Finlor (Fin + Lore)
    46	Zappard (Zap + Leopard)
    47	Voltispike (Volt + Spike)
    48	Wattling (Watt + Gosling)
    49	Jolterm (Jolt + Termite)
    50	Sparkat (Spark + Cat)
    51	Boltile (Bolt + Reptile)
    52	Shocken (Shock + Chicken)
    53	Voltrabit (Volt + Rabbit)
    54	Zappis (Zap + Ibis)
    55	Staticon (Static + Falcon)
    56	Joltisk (Jolt + Isk)
    57	Curris (Current + Suffix)
    58	Sparkite (Spark + Suffix)
    59	Wattling (Watt + Wing)
    60	Wiros (Wire + Suffix)
    61	Aeropuff (Aero + Puff)
    62	Zephyring (Zephyr + Wing)
    63	Cirrofin (Cirrus + Fin)
    64	Avianix (Avian + Nix)
    65	Skyskim (Sky + Skimmer)
    66	Breezara (Breeze + Sahara)
    67	Feathero (Feather + Aero)
    68	Gustern (Gust + Tern)
    69	Winglore (Wing + Lore)
    70	Aerbloom (Aero + Bloom)
    71	Breezly (Breeze + Fly)
    72	Galeon (Gale + Eon)
    73	Draftid (Draft + Suffix)
    74	Plumon (Plumage + Suffix)
    75	Skyro (Sky + Suffix)
    76	Spectroak (Specter + Oak)
    77	Umbraveil (Umbra + Veil)
    78	Phantox (Phantom + Fox)
    79	Shadox (Shadow + Ox)
    80	Wispur (Wisp + Purr)
    81	Eerigull (Eerie + Gull)
    82	Spookat (Spook + Cat)
    83	Ghostis (Ghost + Mantis)
    84	Wraither (Wraith + Otter)
    85	Hauntler (Haunt + Antler)
    86	Shadew (Shade + Dew)
    87	Ghasp (Ghost + Gasp)
    88	Gloomite (Gloom + Suffix)
    89	Phantore (Phantom + Ore)
    90	Wispon (Wisp + Suffix)
    91	Ferroscrap (Ferro + Scrap)
    92	Lithopod (Litho + Pod)
    93	Titancrag (Titan + Crag)
    94	Cupron (Copper + Iron)
    95	Pebblish (Pebble + Fish)
    96	Ferrolon (Ferro + Suffix)
    97	Rockid (Rock + Kid)
    98	Irontoe (Iron + Toe)
    99	Metant (Metal + Ant)
   100	Alloysaur (Alloy + Dinosaur)
END
