M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-03-31T22:58:16-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-31T22:58:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X6.3534Y-3.7241
X6.3534Y-3.9517
M30
